# Generated by Django 5.0.3 on 2024-04-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('dateofbirth', models.DateTimeField(max_length=25)),
                ('marital_status', models.BooleanField(default=False)),
                ('occupation', models.CharField(max_length=25)),
                ('education', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('contactAddress', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Believer'), (1, 'Non-Believer')], default=0)),
                ('occupation', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('adminRole', models.CharField(max_length=100)),
                ('adminDepartment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('contactAddress', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('designatedPermission', models.CharField(max_length=100)),
                ('adminRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('signIn', models.CharField(max_length=50)),
                ('signOut', models.CharField(max_length=50)),
                ('register', models.CharField(max_length=50)),
                ('on_delete', models.BooleanField(default=False)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.clients')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.permission')),
            ],
        ),
    ]
